---
spring:
 profiles: dev
host: 
  domain: item-dev-api123.myhost.com

---
spring:
  profiles: stg
host:
  domain: item-stg-api.myhost.com
  
---
spring:
  profiles: prod
host:
  domain: item-prod-api.myhost.com

